import {chromium} from '../.design-tools/.shared/visual-runtime/node_modules/playwright/index.mjs'
import {mkdir,writeFile} from 'node:fs/promises'
const dir='docs/qa/release';await mkdir(dir,{recursive:true});const b=await chromium.launch({headless:true,channel:'msedge'}),results=[]
try{for(const width of [1440,1920,390]){
 const p=await b.newPage({viewport:{width,height:width===1920?1080:width===390?844:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:4173/');await p.locator('#hero[data-ready=true]').waitFor()
 const unopened=await p.locator('.work-case__thumbnail').count();await p.locator('.floating-company').first().scrollIntoViewIfNeeded();await p.waitForTimeout(700);await p.locator('.floating-company').first().click();await p.waitForTimeout(600)
 const covers=[];for(let i=0;i<5;i++){const cover=p.locator('.work-case__cover').nth(i);await cover.scrollIntoViewIfNeeded();await p.locator('.work-case__thumbnail').nth(i).evaluate(e=>e.decode());await p.waitForTimeout(200);covers.push(await cover.evaluate(e=>{const im=e.querySelector('img');return{href:e.href,target:e.target,rel:e.rel,src:im.getAttribute('src'),alt:im.alt,w:im.naturalWidth,h:im.naturalHeight,fit:getComputedStyle(im).objectFit}}));await p.screenshot({path:`${dir}/${width}-cover${i+1}.png`})}
 const links=await p.locator('.work-case a:not(.work-case__cover)').evaluateAll(es=>es.map(e=>({href:e.href,target:e.target,rel:e.rel,height:e.getBoundingClientRect().height})))
 const popups=[];if(width===1440){for(let i=0;i<5;i++){const promise=p.waitForEvent('popup');await p.locator('.work-case a:not(.work-case__cover)').nth(i).click();const popup=await promise;await popup.waitForLoadState('domcontentloaded',{timeout:12000}).catch(()=>{});popups.push(popup.url());await popup.close()}}
 await p.locator('.work-group[data-category=KOC]').evaluate(e=>e.scrollIntoView({block:'start'}));const closeVisible=await p.locator('.experience-modal__close').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight});const overflow=await p.locator('dialog').evaluate(e=>e.scrollWidth>e.clientWidth)
 await p.locator('.experience-modal__close').click();await p.waitForTimeout(500);await p.goto('http://localhost:4173/#ai-workflow');await p.reload();await p.locator('#hero[data-ready=true]').waitFor();await p.locator('.ai-row').nth(1).scrollIntoViewIfNeeded();await p.locator('.ai-row').nth(1).hover();await p.waitForTimeout(500);await p.screenshot({path:`${dir}/${width}-ai.png`});await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await p.waitForTimeout(1300);await p.screenshot({path:`${dir}/${width}-ending.png`})
 results.push({width,errors,unopened,covers,links,popups,closeVisible,overflow,bodyOverflow:await p.evaluate(()=>document.body.style.overflow)});await p.close()
}await writeFile(`${dir}/results.json`,JSON.stringify(results,null,2));console.log(results)}finally{await b.close()}
